# Generated by Django 2.0.6 on 2018-06-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywarehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_numer',
            new_name='article_number',
        ),
    ]
